name: GitHub Actions $name$
on: [push]
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.$javaVersion$"
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test
    - name: Package
      run: sbt -v -Dfile.encoding=UTF-8 assembly
    - name: Deploy jars to S3
      uses: medlypharmacy/s3-artifacts-action@master
      with:
          aws_access_key_id: \${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: \${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_s3_bucket_name: alebd-dev
          source_path: target/scala-$scalaVersionMajor$/$name$-assembly-$version$.jar
          destination_path: /$bucketS3$/spark/$name$
    
  